<?php
/** @var \Icinga\Web\View $this */
/** @var \Icinga\Module\Aws\Forms\Config\KeysListForm $form */
?>
<form id="<?=
$this->escape($form->getId())
?>" name="<?=
$this->escape($form->getName())
?>" enctype="<?=
$this->escape($form->getEncType())
?>" method="<?=
$this->escape($form->getMethod())
?>" action="<?=
$this->escape($form->getAction())
?>">
    <table class="table-row-selectable common-table" data-base-target="_next">
        <thead>
        <tr>
            <th><?= $this->escape($this->translate('Keys')) ?></th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php
        $keyConfig = $form->getConfig();
        foreach ($keyConfig as $keyName => $config):
            ?>
            <tr>
                <td>
                    <?= $this->qlink(
                        $keyName,
                        'aws/config/editkey',
                        array('key' => $keyName),
                        array(
                            'icon'  => 'edit',
                            'title' => sprintf($this->escape($this->translate('Edit key %s')), $keyName)
                        )
                    ); ?>
                </td>
                <td class="text-right">
                    <?= $this->qlink(
                        '',
                        'aws/config/removekey',
                        array('key' => $keyName),
                        array(
                            'class' => 'action-link',
                            'icon'  => 'cancel',
                            'title' => sprintf($this->escape($this->translate('Remove key %s')), $keyName)
                        )
                    ); ?>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
    <?= $form->getElement($form->getTokenElementName()) ?>
    <?= $form->getElement($form->getUidElementName()) ?>
</form>
